name: "Update dev"

on:
  push:
    branches:
      - dev
      - feat/ga_release

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Print branch
      run: |
        echo "ref" ${{ github.ref }}
        echo "ref_name" ${{ github.ref_name }}
        echo "head_ref" ${{ github.head_ref }}
        echo "base_ref" ${{ github.base_ref }}
