name: artifacts

on:
  push:
    branches:
      - devnet
      - dev
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Print branch
      run: |
        echo "ref" ${{ github.ref }}
        echo "ref_name" ${{ github.ref_name }}
        echo "head_ref" ${{ github.head_ref }}
        echo "base_ref" ${{ github.base_ref }}

    - name: Set version
      id: set_version
      run: echo "GWEMIX_VERSION=1.4.3" >> "$GITHUB_OUTPUT"

    - name: get version
      env:
        GWEMIX_VERSION: ${{ steps.set_version.outputs.GWEMIX_VERSION }}
      run: echo "[XXX] $GWEMIX_VERSION"

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Build Go-WEMIX tarball
      run: USE_ROCKSDB=YES make gwemix.tar.gz

    - name: Stat Go-WEMIX tarball
      run: |
        ls -l build/gwemix.tar.gz
        tar tf build/gwemix.tar.gz

    - name: Move results to artifact
      run: mv build/gwemix.tar.gz gwemix-${{ github.ref_name }}-${{ github.sha }}-linux-amd64-rocksdb.tar.gz

    - name: Upload Go-WEMIX
      uses: actions/upload-artifact@v4
      with:
        name: artifact-${{ github.ref_name }}-${{ github.sha }}
        path: gwemix-${{ github.ref_name }}-${{ github.sha }}-linux-amd64-rocksdb.tar.gz
        retention-days: 7

    - name: Remove results
      run: rm gwemix-${{ github.ref_name }}-${{ github.sha }}-linux-amd64-rocksdb.tar.gz
